<div style="text-align: center;">
<h2>INFSCI 2595 Machine Learning - Fall 2018 </h2>
<h1 style="font-size: 250%;">Assignment #2</h1>
<h3>Due Sunday, 11:59am, 11/18/2018</h3>
<h3>Total points: 100 </h3>
</div>

In [1]:
# Type in your information in the double quotes
firstName = "Deepa"
lastName = "Dorairaj"
pittID = "DED76"

# <h3>  Problem #1. Linear Discriminant Analysis (LDA)and Quadratic Discriminant Analysis(QDA) </h3> 
 ### [30 points]
 
Do not write a code for this part

<h4> Problem #1-1 [10 points]</h4>  <br>
We have a classification problem with one feature $(x)$ and K classes to be classified. The prior probability of
class $k$ is $𝜋_{k} = 𝑃(𝑌 = 𝑘)$. Assume that the feature in class k has Gaussian distribution of
mean $μ_{k}$ and variance $σ^2 (𝒩(μ,𝜎^{2}))$.The variance is the same for all classes. 
Prove that the Bayes’ classifier (that chooses class k with largest $𝑃(𝑌 = 𝑘|𝑥))$ is equivalent to assigning an observation to the class for which the discriminant function $𝛿_{k}(x)$ is
maximized, where 
\begin{array} \\
𝛿_{k}(x) = x\frac{\mu _{k}}{\sigma ^{2}}- \frac{\mu_{2}^{k}}{2\sigma ^{2}}+ log(\pi _{k})
\end{array}
<br> What is the name of this classifier?

### Answer 1-1
#### The name of the above classifier is Linear Discriminant Analysis (LDA).

<h4> Problem #1-2 [15 points]</h4>  <br>
Extend **Problem #1-1** to include **p** features. With features from each class drawn from a
Gaussian distribution with mean vector $μ_{k}$ and covariance matrix $Σ_{k}$ (which is now
different for each class). What is the discriminant function that maximizes **𝑃(𝑌 = 𝑘|𝑥)**. Is
the relationship with the feature vector **x** linear?<br> What is this classifier?

### Answer 1-2
#### This classifier is Quadratic Discriminant Analysis (QDA)

<h4> Problem #1-3 [5 points]</h4>  <br>
- Explain Bias and variance trade-off between the two above classifiers.

### Answer 1-3

#### The difference between the two classifiers is a bias-variance trade-off. With p predictors, estimating a co variance matrix requires estimating p(p+1)/2 parameters. 
#### ~ QDA estimates a separate co variance matrix for each class, so as the number of predictors becomes high, we experience a computational expense. Conversely, if we assume a common co variance matrix, we only have to do the computation once. 
#### ~ LDA is a much less flexible classifier, than QDA, thus has substantially lower variance. However, if the assumption of uniform variance is highly off, then LDA can suffer high bias. In general, LDA tends to be better than QDA if there are relatively few training observations, so therefore reducing variance is crucial. 
#### ~ QDA is recommended if the training set is very large, so that the variance of the classifier is not a major concern.
#### Between Logistic regression LDA and QDA, the biggest things to take into consideration are the type of decision boundary that is required. If highly linear, than LDA and Logistic may prove superior, if non-linear, then QDA may be better.

#### <h3>  Problem #2. Regularization    </h3>
### [15 points]

<h4> Problem #2-1. [3 points]</h4> Answer the following questions 

- What is the main purpose of using regularization?


### Answer 2-1
#### Regularization is mostly used in the field of classification and mainly prevents overfitting. 

<h4> Problem #2-2.Logistic Regression with Ridge Regularization [12 points] </h4>  <br>

In this part, you should download and analyze the Wisconson **"breast_cancer"** dataset. <br>

- Fit logistic regression model using ridge regularization with different values of  C = 0.1, 1, 5, 10, 50, 100, and 1000 (Note that C is the LogisticRegression function argument). For each value, report the estimated coefficients for the fitted model (do not just print summary, make a table with feature names and estimated coefficients)

- What happens to the coefficients as you increase C?

- What happens to the flexibility of the model as you increase C?

In [2]:
from sklearn.datasets import load_breast_cancer
import numpy as np
import pandas as pd

DataCancer=load_breast_cancer()
print(DataCancer.keys())

X_features=DataCancer.data
Y_targetClass=DataCancer.target

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X_features, Y_targetClass, random_state= 0)
from sklearn.linear_model import LogisticRegression
table = pd.DataFrame(columns = [0.1, 1, 5, 10, 50, 100, 1000], index = DataCancer.feature_names)
for c in [0.1, 1, 5, 10, 50, 100, 1000]:
    LogRegModel1 = LogisticRegression(C=c).fit(X_train, Y_train)
    coef = LogRegModel1.coef_
    table[c]=coef.T
print(table)

                           0.1       1.0       5.0       10.0      50.0    \
mean radius              0.535436  1.722166  2.725981  3.058715  3.594745   
mean texture             0.076798  0.089805  0.149395  0.125832  0.167928   
mean perimeter           0.403791  0.105985 -0.119744 -0.101074 -0.203368   
mean area               -0.012596 -0.007134 -0.005244 -0.011125 -0.011994   
mean smoothness         -0.020002 -0.128409 -0.308702 -0.737346 -1.391057   
mean compactness        -0.086440 -0.333501 -0.567312 -0.560991 -0.569680   
mean concavity          -0.122754 -0.499364 -0.900420 -1.093522 -1.328377   
mean concave points     -0.053632 -0.265081 -0.567216 -1.237483 -2.264764   
mean symmetry           -0.039820 -0.267607 -0.651811 -1.558487 -2.846979   
mean fractal dimension  -0.004791 -0.021495 -0.033193  0.047167  0.172525   
radius error             0.022073  0.036473  0.013441  0.134060  0.362081   
texture error            0.205684  0.986553  1.991618  1.760838  2.290579   

### Answer 2-2

#### • Large C means less regularization strength
#### • very large C means no regularization
#### • Small C means more regularization and coefficients will be close to zero
#### • C is inversely proportional to alpha in the regression functions, hence smaller C specifies stronger regularization. Therefore, Coefficients decrease when C increases.
#### • The model is flexible when C increases, Flexibility of the model reduces when C is very small.

### <h3>  Problem #3. Logistic Regression and Unbalanced Datasets  </h3> 
### [25 points]


We fit a logistic regression model to predict the probability that an individual will default on his/her credit card balance. We used the total balance (single feature) to fit the model and got the results shown in the table below.

<h4> Problem #3-1. [5 points]</h4> Prediciton with Logistic regression <br>

|Table|Coefficient|Std.error|Z-statistic|P-Value|
|:--:|:-------------------------------:|
|Intercept|-10.6513|0.3612|-29.5|<0.0001|
|balance|0.0055|0.002|24.9|<0.0001|

(You can refer to page 14 in the our slides "Logistic Regression.pdf" if the above table does not show well.)

- What is the parametric model used in logistic regression?
- What is the class label of an individual with a balance equals to 15,000 dollar? What is the class label of an individual with balance equals to 800 dollar? (Write a python function which takes two inputs (feature, model_parameters) and returns the class labels for the data). default is class 1 and non-default is class 0.

### Answer 3-1 

#### • The parameter model used in logistic regression has a logit that is linear with X(feature).

In [4]:
import math
def label(bal,coef):
    intercept = coef[0]
    coef = coef[1]
    p = math.exp(intercept + coef * bal)/(1+math.exp(intercept + coef * bal))
    print('for balance %d dollar, label is' %bal)
    if p>= 0.5:
        print('1, high probability to default')
    else:
        print('0, low probability to default')
coef = [-10.6513,0.0055]
label(15000, coef)
print('and')
label(800, coef)

for balance 15000 dollar, label is
1, high probability to default
and
for balance 800 dollar, label is
0, low probability to default


<h4> Problem #3-2. [10 points]</h4>  <br>

The coefficients of logistic regression are obtained by maximizing the likelihood function

\begin{array} \\
l(\beta) = \prod_{i:y_{i}=1} P(y_{i} = 1|x)\prod_{i{}':y_{{i}'}=0} (1-P(y_{{i}'} = 1|x))
\end{array}
Show that maximizing the
likelihood function is equivalent to minimizing the cost function $J(\beta)$, such that.
\begin{array} \\
J(\beta) = -\sum [y_{i} log(P(y_{i} = 1|x)) + (1- y_{i})log(1- P(y_{i} = 1|x))]
\end{array}


Here $n$ is the number training examples. Mention one possible method for obtaining the
optimal coefficients.

<h4> Problem #3-3 [10 points]</h4> <br>
In a fraud detection system, a QDA classifier’s confusion matrix is found to be:

|        |Predicted Class - Not fraud| Predicted Class - fraud|
|:--:|:-------------------------------:|
|Actual class – Not fraud|1200|25|
|Actual class – fraud|30|7|

- Is dataset balanced? Why?
- Evaluate the overall error rate <br>
- Evaluate the precision and the recall <br>


### Answer 3-3 

#### The given dataset is not balanced because majority of cases are not fraud and ver small minority of cases are under fraud. A normal balanced dataset will have 50/50 or 60/40 distribution.

In [5]:
#From the above confusion matrix
TN = 1200
FP = 25
FN = 30
TP = 7

In [6]:
# Error rate
(FN+FP)/(TP+TN+FN+FP)

0.043581616481774964

In [7]:
#RECALL
TP/(TP+FN)

0.1891891891891892

In [8]:
#PRECISION
TP/(TP+FP)

0.21875

### <h3>  Problem #4. SVM, Decision Trees, MLP Classification   </h3> 
### [30 points]

In this problem, you will use different classification methods, SVM, Decision Tree and MLP; and find their accuracies using the test data. 
We will also use the Wisconson **"breast_cancer"** dataset.
In all of the following subparts, use random_state=0 when you split the dataset into train and test and **standardize** the data.

In [9]:
# write your code here
import numpy as np
import pandas as pd
from sklearn import datasets 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.datasets import load_breast_cancer
  
dataset = load_breast_cancer()

X_train, X_test, y_train, y_test= train_test_split(dataset.data, dataset.target, random_state= 0)

# standardize data
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler().fit(X_train)
X_train_transformed= scaler.transform(X_train)
X_test_transformed= scaler.transform(X_test)

<h4> Problem #4-1.  Classification with SVM [10 points]</h4><br>
- How does the Radial Basis Function Kernel in SVM measure the similarity between a test point and a training example?
- Fit an SVM classifier with a radial basis function kernel, with gamma =0.1, and regularization parameter C set to 10. Use the classifier to predict class labels for the test data. 
- Calculate the accuracy and confusion matrix on the test data.

The value of the RBF kernel decreases with distance and ranges between zero and one, support vector machines and other models employing the kernel trick do not scale well to large numbers of training samples.

In [10]:
from sklearn.svm import SVC
svmModel=SVC(kernel='rbf', gamma=0.1, C=10).fit(X_train_transformed, y_train)
svmModel.classes_

array([0, 1])

In [11]:
y_pred = svmModel.predict(X_test_transformed)
# confusion matrix on test data
confusion_matrix(y_test, y_pred)

array([[52,  1],
       [ 4, 86]])

In [12]:
from sklearn.metrics import accuracy_score 
# accuracy on test data
accuracy_score(y_test,y_pred)

0.965034965034965

In [13]:
# class labels for test data
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0])

<h4> Problem #4-2.  Classification with Decisin Tree (DT) [10 points]</h4><br>
- In this part, use DT classification method on the training data. Set the maximum depth of the tree to five. Then use the classifier to predict class labels for the test data. Calculate the accuracy and confusion matrix on the test data.
- Use Adaboost to combine four decision trees each of max_depth of five. Use random_state=0 in adaboost. Find the test accuracy. 

In [14]:
from sklearn.tree import DecisionTreeClassifier
treeModel=DecisionTreeClassifier(max_depth=5)
treeModel.fit(X_train_transformed,y_train)
treeModel.score(X_test_transformed,y_test)

0.9300699300699301

In [15]:
y_pred1 = treeModel.predict(X_test_transformed)
# confusion matrix on test data
confusion_matrix(y_test, y_pred1)

array([[51,  2],
       [ 8, 82]])

In [16]:
# test accuracy
accuracy_score(y_test,y_pred1)

0.9300699300699301

In [17]:
from sklearn.ensemble import AdaBoostClassifier
BoostModel= AdaBoostClassifier(n_estimators=4, base_estimator = DecisionTreeClassifier(max_depth=5),random_state=0)
BoostModel.fit(X_train_transformed,y_train)
y_pred2 = BoostModel.predict(X_test_transformed)
# test accuracy
accuracy_score(y_test,y_pred2)

0.9370629370629371

<h4> Problem #4-3 [10 points]</h4>

Follow steps to answer questions to build a neural network using MLPClassifier from sklearn.neural_network. 
- Build a model that has two hidden layers, the first layer has 10 neurons and second layer has 5 neurons. 
- Use 'relu' activation function, and set the regularization parameter alpha=0.5. 
- Set max_iter=1000; Set the random_state=0.
- Use stochastic gradient descent (sgd) to solve the optimization  problem
- Report accuracy, confusion matrix, precision, and recall 

In [18]:
from sklearn.neural_network import MLPClassifier
MLPmodelc=MLPClassifier(solver='sgd', max_iter = 1000, activation='relu', random_state=0, 
                       hidden_layer_sizes=[10,5], alpha=0.5).fit(X_train_transformed,y_train)

In [19]:
y_pred11 = MLPmodelc.predict(X_test_transformed)
# confusion matrix
confusion_matrix(y_test, y_pred11)

array([[52,  1],
       [ 2, 88]])

In [20]:
# accuracy
accuracy_score(y_test,y_pred11)

0.9790209790209791

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred11))

             precision    recall  f1-score   support

          0       0.96      0.98      0.97        53
          1       0.99      0.98      0.98        90

avg / total       0.98      0.98      0.98       143

